stat_card_data = [
    {
        "title": "E-Waste Generado (2019)",
        "value": "1,349 kt",
        "sub_detail": "Promedio: 6.7 kg/hab",
        "icon": "trash-2",
        "color": "cyan",
        "chart_data": [
            {"v": 944},
            {"v": 984},
            {"v": 1025},
            {"v": 1065},
            {"v": 1106},
            {"v": 1146},
            {"v": 1187},
            {"v": 1227},
            {"v": 1268},
            {"v": 1308},
        ],
    },
    {
        "title": "Tasa de Recolección Formal",
        "value": "2.9%",
        "sub_detail": "1,311 kt no gestionado (97.1%)",
        "icon": "recycle",
        "color": "purple",
        "chart_data": [
            {"v": 2},
            {"v": 2},
            {"v": 2},
            {"v": 2},
            {"v": 2},
            {"v": 2},
            {"v": 2},
            {"v": 2},
            {"v": 2},
            {"v": 2},
        ],
    },
    {
        "title": "Valor Económico Potencial",
        "value": "$1,735 M",
        "sub_detail": "$1,686 M perdidos anualmente",
        "icon": "dollar-sign",
        "color": "teal",
        "chart_data": [
            {"v": 1578},
            {"v": 1312},
            {"v": 1420},
            {"v": 1398},
            {"v": 1620},
            {"v": 1594},
            {"v": 1688},
            {"v": 1338},
            {"v": 1484},
            {"v": 1314},
        ],
    },
]
resource_allocation_data = [
    {"name": "Processing Power", "value": 42, "color": "cyan"},
    {"name": "Memory Allocation", "value": 68, "color": "pink"},
    {"name": "Network Bandwidth", "value": 35, "color": "blue"},
]
quick_actions_data = [
    {"name": "Security Scan", "icon": "shield-check"},
    {"name": "Sync Data", "icon": "refresh-cw"},
    {"name": "Backup", "icon": "database"},
    {"name": "Console", "icon": "terminal"},
]
performance_chart_data = [
    {"time": "00:00", "CPU": 28, "Memory": 25, "Network": 15},
    {"time": "03:00", "CPU": 32, "Memory": 30, "Network": 20},
    {"time": "06:00", "CPU": 30, "Memory": 35, "Network": 25},
    {"time": "09:00", "CPU": 35, "Memory": 40, "Network": 30},
    {"time": "12:00", "CPU": 38, "Memory": 42, "Network": 35},
    {"time": "15:00", "CPU": 36, "Memory": 40, "Network": 32},
    {"time": "18:00", "CPU": 34, "Memory": 38, "Network": 30},
    {"time": "21:00", "CPU": 32, "Memory": 35, "Network": 28},
    {"time": "24:00", "CPU": 30, "Memory": 33, "Network": 25},
]